// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package user;

public final class User {
  private User() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UsuarioOrBuilder extends
      // @@protoc_insertion_point(interface_extends:user.Usuario)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string nombre = 1;</code>
     */
    java.lang.String getNombre();
    /**
     * <code>string nombre = 1;</code>
     */
    com.google.protobuf.ByteString
        getNombreBytes();

    /**
     * <code>string apellido = 2;</code>
     */
    java.lang.String getApellido();
    /**
     * <code>string apellido = 2;</code>
     */
    com.google.protobuf.ByteString
        getApellidoBytes();

    /**
     * <code>int32 dni = 3;</code>
     */
    int getDni();

    /**
     * <code>string email = 4;</code>
     */
    java.lang.String getEmail();
    /**
     * <code>string email = 4;</code>
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <code>string usuario = 5;</code>
     */
    java.lang.String getUsuario();
    /**
     * <code>string usuario = 5;</code>
     */
    com.google.protobuf.ByteString
        getUsuarioBytes();

    /**
     * <code>string clave = 6;</code>
     */
    java.lang.String getClave();
    /**
     * <code>string clave = 6;</code>
     */
    com.google.protobuf.ByteString
        getClaveBytes();
  }
  /**
   * Protobuf type {@code user.Usuario}
   */
  public  static final class Usuario extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:user.Usuario)
      UsuarioOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Usuario.newBuilder() to construct.
    private Usuario(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Usuario() {
      nombre_ = "";
      apellido_ = "";
      dni_ = 0;
      email_ = "";
      usuario_ = "";
      clave_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Usuario(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              nombre_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              apellido_ = s;
              break;
            }
            case 24: {

              dni_ = input.readInt32();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              email_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              usuario_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              clave_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return user.User.internal_static_user_Usuario_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return user.User.internal_static_user_Usuario_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              user.User.Usuario.class, user.User.Usuario.Builder.class);
    }

    public static final int NOMBRE_FIELD_NUMBER = 1;
    private volatile java.lang.Object nombre_;
    /**
     * <code>string nombre = 1;</code>
     */
    public java.lang.String getNombre() {
      java.lang.Object ref = nombre_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nombre_ = s;
        return s;
      }
    }
    /**
     * <code>string nombre = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNombreBytes() {
      java.lang.Object ref = nombre_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nombre_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int APELLIDO_FIELD_NUMBER = 2;
    private volatile java.lang.Object apellido_;
    /**
     * <code>string apellido = 2;</code>
     */
    public java.lang.String getApellido() {
      java.lang.Object ref = apellido_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        apellido_ = s;
        return s;
      }
    }
    /**
     * <code>string apellido = 2;</code>
     */
    public com.google.protobuf.ByteString
        getApellidoBytes() {
      java.lang.Object ref = apellido_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        apellido_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DNI_FIELD_NUMBER = 3;
    private int dni_;
    /**
     * <code>int32 dni = 3;</code>
     */
    public int getDni() {
      return dni_;
    }

    public static final int EMAIL_FIELD_NUMBER = 4;
    private volatile java.lang.Object email_;
    /**
     * <code>string email = 4;</code>
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      }
    }
    /**
     * <code>string email = 4;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USUARIO_FIELD_NUMBER = 5;
    private volatile java.lang.Object usuario_;
    /**
     * <code>string usuario = 5;</code>
     */
    public java.lang.String getUsuario() {
      java.lang.Object ref = usuario_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        usuario_ = s;
        return s;
      }
    }
    /**
     * <code>string usuario = 5;</code>
     */
    public com.google.protobuf.ByteString
        getUsuarioBytes() {
      java.lang.Object ref = usuario_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        usuario_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLAVE_FIELD_NUMBER = 6;
    private volatile java.lang.Object clave_;
    /**
     * <code>string clave = 6;</code>
     */
    public java.lang.String getClave() {
      java.lang.Object ref = clave_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clave_ = s;
        return s;
      }
    }
    /**
     * <code>string clave = 6;</code>
     */
    public com.google.protobuf.ByteString
        getClaveBytes() {
      java.lang.Object ref = clave_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clave_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNombreBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, nombre_);
      }
      if (!getApellidoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, apellido_);
      }
      if (dni_ != 0) {
        output.writeInt32(3, dni_);
      }
      if (!getEmailBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, email_);
      }
      if (!getUsuarioBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, usuario_);
      }
      if (!getClaveBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, clave_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNombreBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, nombre_);
      }
      if (!getApellidoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, apellido_);
      }
      if (dni_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, dni_);
      }
      if (!getEmailBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, email_);
      }
      if (!getUsuarioBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, usuario_);
      }
      if (!getClaveBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, clave_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof user.User.Usuario)) {
        return super.equals(obj);
      }
      user.User.Usuario other = (user.User.Usuario) obj;

      boolean result = true;
      result = result && getNombre()
          .equals(other.getNombre());
      result = result && getApellido()
          .equals(other.getApellido());
      result = result && (getDni()
          == other.getDni());
      result = result && getEmail()
          .equals(other.getEmail());
      result = result && getUsuario()
          .equals(other.getUsuario());
      result = result && getClave()
          .equals(other.getClave());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NOMBRE_FIELD_NUMBER;
      hash = (53 * hash) + getNombre().hashCode();
      hash = (37 * hash) + APELLIDO_FIELD_NUMBER;
      hash = (53 * hash) + getApellido().hashCode();
      hash = (37 * hash) + DNI_FIELD_NUMBER;
      hash = (53 * hash) + getDni();
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEmail().hashCode();
      hash = (37 * hash) + USUARIO_FIELD_NUMBER;
      hash = (53 * hash) + getUsuario().hashCode();
      hash = (37 * hash) + CLAVE_FIELD_NUMBER;
      hash = (53 * hash) + getClave().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static user.User.Usuario parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static user.User.Usuario parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static user.User.Usuario parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static user.User.Usuario parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static user.User.Usuario parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static user.User.Usuario parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static user.User.Usuario parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static user.User.Usuario parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static user.User.Usuario parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static user.User.Usuario parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static user.User.Usuario parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static user.User.Usuario parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(user.User.Usuario prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code user.Usuario}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:user.Usuario)
        user.User.UsuarioOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return user.User.internal_static_user_Usuario_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return user.User.internal_static_user_Usuario_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                user.User.Usuario.class, user.User.Usuario.Builder.class);
      }

      // Construct using user.User.Usuario.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        nombre_ = "";

        apellido_ = "";

        dni_ = 0;

        email_ = "";

        usuario_ = "";

        clave_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return user.User.internal_static_user_Usuario_descriptor;
      }

      @java.lang.Override
      public user.User.Usuario getDefaultInstanceForType() {
        return user.User.Usuario.getDefaultInstance();
      }

      @java.lang.Override
      public user.User.Usuario build() {
        user.User.Usuario result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public user.User.Usuario buildPartial() {
        user.User.Usuario result = new user.User.Usuario(this);
        result.nombre_ = nombre_;
        result.apellido_ = apellido_;
        result.dni_ = dni_;
        result.email_ = email_;
        result.usuario_ = usuario_;
        result.clave_ = clave_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof user.User.Usuario) {
          return mergeFrom((user.User.Usuario)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(user.User.Usuario other) {
        if (other == user.User.Usuario.getDefaultInstance()) return this;
        if (!other.getNombre().isEmpty()) {
          nombre_ = other.nombre_;
          onChanged();
        }
        if (!other.getApellido().isEmpty()) {
          apellido_ = other.apellido_;
          onChanged();
        }
        if (other.getDni() != 0) {
          setDni(other.getDni());
        }
        if (!other.getEmail().isEmpty()) {
          email_ = other.email_;
          onChanged();
        }
        if (!other.getUsuario().isEmpty()) {
          usuario_ = other.usuario_;
          onChanged();
        }
        if (!other.getClave().isEmpty()) {
          clave_ = other.clave_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        user.User.Usuario parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (user.User.Usuario) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object nombre_ = "";
      /**
       * <code>string nombre = 1;</code>
       */
      public java.lang.String getNombre() {
        java.lang.Object ref = nombre_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nombre_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string nombre = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNombreBytes() {
        java.lang.Object ref = nombre_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nombre_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string nombre = 1;</code>
       */
      public Builder setNombre(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nombre_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string nombre = 1;</code>
       */
      public Builder clearNombre() {
        
        nombre_ = getDefaultInstance().getNombre();
        onChanged();
        return this;
      }
      /**
       * <code>string nombre = 1;</code>
       */
      public Builder setNombreBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nombre_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object apellido_ = "";
      /**
       * <code>string apellido = 2;</code>
       */
      public java.lang.String getApellido() {
        java.lang.Object ref = apellido_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          apellido_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string apellido = 2;</code>
       */
      public com.google.protobuf.ByteString
          getApellidoBytes() {
        java.lang.Object ref = apellido_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          apellido_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string apellido = 2;</code>
       */
      public Builder setApellido(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        apellido_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string apellido = 2;</code>
       */
      public Builder clearApellido() {
        
        apellido_ = getDefaultInstance().getApellido();
        onChanged();
        return this;
      }
      /**
       * <code>string apellido = 2;</code>
       */
      public Builder setApellidoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        apellido_ = value;
        onChanged();
        return this;
      }

      private int dni_ ;
      /**
       * <code>int32 dni = 3;</code>
       */
      public int getDni() {
        return dni_;
      }
      /**
       * <code>int32 dni = 3;</code>
       */
      public Builder setDni(int value) {
        
        dni_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 dni = 3;</code>
       */
      public Builder clearDni() {
        
        dni_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object email_ = "";
      /**
       * <code>string email = 4;</code>
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string email = 4;</code>
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string email = 4;</code>
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string email = 4;</code>
       */
      public Builder clearEmail() {
        
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>string email = 4;</code>
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        email_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object usuario_ = "";
      /**
       * <code>string usuario = 5;</code>
       */
      public java.lang.String getUsuario() {
        java.lang.Object ref = usuario_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          usuario_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string usuario = 5;</code>
       */
      public com.google.protobuf.ByteString
          getUsuarioBytes() {
        java.lang.Object ref = usuario_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          usuario_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string usuario = 5;</code>
       */
      public Builder setUsuario(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        usuario_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string usuario = 5;</code>
       */
      public Builder clearUsuario() {
        
        usuario_ = getDefaultInstance().getUsuario();
        onChanged();
        return this;
      }
      /**
       * <code>string usuario = 5;</code>
       */
      public Builder setUsuarioBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        usuario_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object clave_ = "";
      /**
       * <code>string clave = 6;</code>
       */
      public java.lang.String getClave() {
        java.lang.Object ref = clave_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          clave_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string clave = 6;</code>
       */
      public com.google.protobuf.ByteString
          getClaveBytes() {
        java.lang.Object ref = clave_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clave_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string clave = 6;</code>
       */
      public Builder setClave(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        clave_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string clave = 6;</code>
       */
      public Builder clearClave() {
        
        clave_ = getDefaultInstance().getClave();
        onChanged();
        return this;
      }
      /**
       * <code>string clave = 6;</code>
       */
      public Builder setClaveBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        clave_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:user.Usuario)
    }

    // @@protoc_insertion_point(class_scope:user.Usuario)
    private static final user.User.Usuario DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new user.User.Usuario();
    }

    public static user.User.Usuario getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Usuario>
        PARSER = new com.google.protobuf.AbstractParser<Usuario>() {
      @java.lang.Override
      public Usuario parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Usuario(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Usuario> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Usuario> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public user.User.Usuario getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface IdUsuarioOrBuilder extends
      // @@protoc_insertion_point(interface_extends:user.IdUsuario)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 idUsuario = 1;</code>
     */
    int getIdUsuario();
  }
  /**
   * Protobuf type {@code user.IdUsuario}
   */
  public  static final class IdUsuario extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:user.IdUsuario)
      IdUsuarioOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use IdUsuario.newBuilder() to construct.
    private IdUsuario(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private IdUsuario() {
      idUsuario_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private IdUsuario(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              idUsuario_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return user.User.internal_static_user_IdUsuario_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return user.User.internal_static_user_IdUsuario_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              user.User.IdUsuario.class, user.User.IdUsuario.Builder.class);
    }

    public static final int IDUSUARIO_FIELD_NUMBER = 1;
    private int idUsuario_;
    /**
     * <code>int32 idUsuario = 1;</code>
     */
    public int getIdUsuario() {
      return idUsuario_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (idUsuario_ != 0) {
        output.writeInt32(1, idUsuario_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (idUsuario_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, idUsuario_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof user.User.IdUsuario)) {
        return super.equals(obj);
      }
      user.User.IdUsuario other = (user.User.IdUsuario) obj;

      boolean result = true;
      result = result && (getIdUsuario()
          == other.getIdUsuario());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + IDUSUARIO_FIELD_NUMBER;
      hash = (53 * hash) + getIdUsuario();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static user.User.IdUsuario parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static user.User.IdUsuario parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static user.User.IdUsuario parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static user.User.IdUsuario parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static user.User.IdUsuario parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static user.User.IdUsuario parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static user.User.IdUsuario parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static user.User.IdUsuario parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static user.User.IdUsuario parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static user.User.IdUsuario parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static user.User.IdUsuario parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static user.User.IdUsuario parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(user.User.IdUsuario prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code user.IdUsuario}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:user.IdUsuario)
        user.User.IdUsuarioOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return user.User.internal_static_user_IdUsuario_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return user.User.internal_static_user_IdUsuario_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                user.User.IdUsuario.class, user.User.IdUsuario.Builder.class);
      }

      // Construct using user.User.IdUsuario.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        idUsuario_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return user.User.internal_static_user_IdUsuario_descriptor;
      }

      @java.lang.Override
      public user.User.IdUsuario getDefaultInstanceForType() {
        return user.User.IdUsuario.getDefaultInstance();
      }

      @java.lang.Override
      public user.User.IdUsuario build() {
        user.User.IdUsuario result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public user.User.IdUsuario buildPartial() {
        user.User.IdUsuario result = new user.User.IdUsuario(this);
        result.idUsuario_ = idUsuario_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof user.User.IdUsuario) {
          return mergeFrom((user.User.IdUsuario)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(user.User.IdUsuario other) {
        if (other == user.User.IdUsuario.getDefaultInstance()) return this;
        if (other.getIdUsuario() != 0) {
          setIdUsuario(other.getIdUsuario());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        user.User.IdUsuario parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (user.User.IdUsuario) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int idUsuario_ ;
      /**
       * <code>int32 idUsuario = 1;</code>
       */
      public int getIdUsuario() {
        return idUsuario_;
      }
      /**
       * <code>int32 idUsuario = 1;</code>
       */
      public Builder setIdUsuario(int value) {
        
        idUsuario_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 idUsuario = 1;</code>
       */
      public Builder clearIdUsuario() {
        
        idUsuario_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:user.IdUsuario)
    }

    // @@protoc_insertion_point(class_scope:user.IdUsuario)
    private static final user.User.IdUsuario DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new user.User.IdUsuario();
    }

    public static user.User.IdUsuario getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<IdUsuario>
        PARSER = new com.google.protobuf.AbstractParser<IdUsuario>() {
      @java.lang.Override
      public IdUsuario parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new IdUsuario(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<IdUsuario> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<IdUsuario> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public user.User.IdUsuario getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UsuarioLoginOrBuilder extends
      // @@protoc_insertion_point(interface_extends:user.UsuarioLogin)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string nombre = 1;</code>
     */
    java.lang.String getNombre();
    /**
     * <code>string nombre = 1;</code>
     */
    com.google.protobuf.ByteString
        getNombreBytes();

    /**
     * <code>string clave = 2;</code>
     */
    java.lang.String getClave();
    /**
     * <code>string clave = 2;</code>
     */
    com.google.protobuf.ByteString
        getClaveBytes();
  }
  /**
   * Protobuf type {@code user.UsuarioLogin}
   */
  public  static final class UsuarioLogin extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:user.UsuarioLogin)
      UsuarioLoginOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UsuarioLogin.newBuilder() to construct.
    private UsuarioLogin(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UsuarioLogin() {
      nombre_ = "";
      clave_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UsuarioLogin(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              nombre_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              clave_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return user.User.internal_static_user_UsuarioLogin_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return user.User.internal_static_user_UsuarioLogin_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              user.User.UsuarioLogin.class, user.User.UsuarioLogin.Builder.class);
    }

    public static final int NOMBRE_FIELD_NUMBER = 1;
    private volatile java.lang.Object nombre_;
    /**
     * <code>string nombre = 1;</code>
     */
    public java.lang.String getNombre() {
      java.lang.Object ref = nombre_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nombre_ = s;
        return s;
      }
    }
    /**
     * <code>string nombre = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNombreBytes() {
      java.lang.Object ref = nombre_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nombre_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLAVE_FIELD_NUMBER = 2;
    private volatile java.lang.Object clave_;
    /**
     * <code>string clave = 2;</code>
     */
    public java.lang.String getClave() {
      java.lang.Object ref = clave_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clave_ = s;
        return s;
      }
    }
    /**
     * <code>string clave = 2;</code>
     */
    public com.google.protobuf.ByteString
        getClaveBytes() {
      java.lang.Object ref = clave_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clave_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNombreBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, nombre_);
      }
      if (!getClaveBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, clave_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNombreBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, nombre_);
      }
      if (!getClaveBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, clave_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof user.User.UsuarioLogin)) {
        return super.equals(obj);
      }
      user.User.UsuarioLogin other = (user.User.UsuarioLogin) obj;

      boolean result = true;
      result = result && getNombre()
          .equals(other.getNombre());
      result = result && getClave()
          .equals(other.getClave());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NOMBRE_FIELD_NUMBER;
      hash = (53 * hash) + getNombre().hashCode();
      hash = (37 * hash) + CLAVE_FIELD_NUMBER;
      hash = (53 * hash) + getClave().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static user.User.UsuarioLogin parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static user.User.UsuarioLogin parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static user.User.UsuarioLogin parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static user.User.UsuarioLogin parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static user.User.UsuarioLogin parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static user.User.UsuarioLogin parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static user.User.UsuarioLogin parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static user.User.UsuarioLogin parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static user.User.UsuarioLogin parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static user.User.UsuarioLogin parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static user.User.UsuarioLogin parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static user.User.UsuarioLogin parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(user.User.UsuarioLogin prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code user.UsuarioLogin}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:user.UsuarioLogin)
        user.User.UsuarioLoginOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return user.User.internal_static_user_UsuarioLogin_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return user.User.internal_static_user_UsuarioLogin_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                user.User.UsuarioLogin.class, user.User.UsuarioLogin.Builder.class);
      }

      // Construct using user.User.UsuarioLogin.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        nombre_ = "";

        clave_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return user.User.internal_static_user_UsuarioLogin_descriptor;
      }

      @java.lang.Override
      public user.User.UsuarioLogin getDefaultInstanceForType() {
        return user.User.UsuarioLogin.getDefaultInstance();
      }

      @java.lang.Override
      public user.User.UsuarioLogin build() {
        user.User.UsuarioLogin result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public user.User.UsuarioLogin buildPartial() {
        user.User.UsuarioLogin result = new user.User.UsuarioLogin(this);
        result.nombre_ = nombre_;
        result.clave_ = clave_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof user.User.UsuarioLogin) {
          return mergeFrom((user.User.UsuarioLogin)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(user.User.UsuarioLogin other) {
        if (other == user.User.UsuarioLogin.getDefaultInstance()) return this;
        if (!other.getNombre().isEmpty()) {
          nombre_ = other.nombre_;
          onChanged();
        }
        if (!other.getClave().isEmpty()) {
          clave_ = other.clave_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        user.User.UsuarioLogin parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (user.User.UsuarioLogin) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object nombre_ = "";
      /**
       * <code>string nombre = 1;</code>
       */
      public java.lang.String getNombre() {
        java.lang.Object ref = nombre_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nombre_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string nombre = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNombreBytes() {
        java.lang.Object ref = nombre_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nombre_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string nombre = 1;</code>
       */
      public Builder setNombre(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nombre_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string nombre = 1;</code>
       */
      public Builder clearNombre() {
        
        nombre_ = getDefaultInstance().getNombre();
        onChanged();
        return this;
      }
      /**
       * <code>string nombre = 1;</code>
       */
      public Builder setNombreBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nombre_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object clave_ = "";
      /**
       * <code>string clave = 2;</code>
       */
      public java.lang.String getClave() {
        java.lang.Object ref = clave_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          clave_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string clave = 2;</code>
       */
      public com.google.protobuf.ByteString
          getClaveBytes() {
        java.lang.Object ref = clave_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clave_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string clave = 2;</code>
       */
      public Builder setClave(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        clave_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string clave = 2;</code>
       */
      public Builder clearClave() {
        
        clave_ = getDefaultInstance().getClave();
        onChanged();
        return this;
      }
      /**
       * <code>string clave = 2;</code>
       */
      public Builder setClaveBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        clave_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:user.UsuarioLogin)
    }

    // @@protoc_insertion_point(class_scope:user.UsuarioLogin)
    private static final user.User.UsuarioLogin DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new user.User.UsuarioLogin();
    }

    public static user.User.UsuarioLogin getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UsuarioLogin>
        PARSER = new com.google.protobuf.AbstractParser<UsuarioLogin>() {
      @java.lang.Override
      public UsuarioLogin parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UsuarioLogin(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UsuarioLogin> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UsuarioLogin> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public user.User.UsuarioLogin getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_Usuario_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_Usuario_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_IdUsuario_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_IdUsuario_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_UsuarioLogin_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_UsuarioLogin_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nuser.proto\022\004user\"g\n\007Usuario\022\016\n\006nombre\030" +
      "\001 \001(\t\022\020\n\010apellido\030\002 \001(\t\022\013\n\003dni\030\003 \001(\005\022\r\n\005" +
      "email\030\004 \001(\t\022\017\n\007usuario\030\005 \001(\t\022\r\n\005clave\030\006 " +
      "\001(\t\"\036\n\tIdUsuario\022\021\n\tidUsuario\030\001 \001(\005\"-\n\014U" +
      "suarioLogin\022\016\n\006nombre\030\001 \001(\t\022\r\n\005clave\030\002 \001" +
      "(\t2d\n\016UsuarioService\022&\n\004Post\022\r.user.Usua" +
      "rio\032\017.user.IdUsuario\022*\n\005Login\022\022.user.Usu" +
      "arioLogin\032\r.user.UsuarioB\032\252\002\027RetroShop_C" +
      "lient.Protosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_user_Usuario_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_user_Usuario_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_Usuario_descriptor,
        new java.lang.String[] { "Nombre", "Apellido", "Dni", "Email", "Usuario", "Clave", });
    internal_static_user_IdUsuario_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_user_IdUsuario_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_IdUsuario_descriptor,
        new java.lang.String[] { "IdUsuario", });
    internal_static_user_UsuarioLogin_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_user_UsuarioLogin_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_UsuarioLogin_descriptor,
        new java.lang.String[] { "Nombre", "Clave", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
